version: "3.8"

services:
  producer:
    build:
      context: .
      dockerfile: Dockerfile.producer  # Reference the correct Dockerfile
    networks:
      - my_network  # Attach to a custom network

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer  # Reference the correct Dockerfile
    depends_on:
      - producer  # Ensure the producer starts first
    networks:
      - my_network  # Connect to the same network
    volumes:
      - data_volume:/data  # Persistent storage for received data

networks:
  my_network:  # Define a network to allow communication
    driver: bridge # We used bridge because we can reference the producer and consumer by their names.
    # Also, we do not care about the containers communicating with the host, so its better to have an isolated network

volumes:
  data_volume:  # Define a volume for persistent storage

