version: "3.8"

services:
  producer:
    build:
      context: .
      dockerfile: Dockerfile.producer  # Reference the Dockerfile
    networks:
      - my_network  # connect to custom network: my_network

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer #reference the consumer dockerfile
    depends_on:
      - producer  # make sure producer stars first
    networks:
      - my_network  # Connect to the same network
    volumes:
      - data_volume:/data  # connect to a volume

networks:
  my_network:  # Define a network to allow communication
    driver: bridge # We used bridge because we can reference the producer and consumer by their names.
    # Also, we do not care about the containers communicating with the host, so its better to have an isolated network

volumes:
  data_volume:  # Define a volume for logging of the numbers

